# fly.toml app configuration file generated for yofication on 2023-12-13T16:14:54+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "yofication"
primary_region = "cdg"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
  swap_size_mb = 512
