version: 2

jobs:
  test:
    docker:
      - image: circleci/rust
    steps:
      - checkout
      - run:
          name: Test
          command: cargo test
  frequencies:
    docker:
      - image: circleci/rust
    steps:
      - checkout
      - run:
          name: Generate frequencies and all-pages
          command: |
            mkdir results
            cargo run --bin frequencies --release
          no_output_timeout: 70m
      - run:
          name: Update frequencies on github
          command: ./update_frequencies_on_github.sh

workflows:
  version: 2
  commit:
    jobs:
      - test
  regular_test:
    jobs:
      - test
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
  frequencies_cron:
    jobs:
      - frequencies
    # twice per month (1th and 15th day of month)
    triggers:
      - schedule:
          # https://crontab.guru/#33_3_1_*_*
          cron: "33 3 1 * *"
          filters:
            branches:
              only:
                - master
      - schedule:
          # https://crontab.guru/#33_3_15_*_*
          cron: "33 3 15 * *"
          filters:
            branches:
              only:
                - master
  frequencies:
#    чтобы инициировать подсчёт частот нужно добавить тег frequencies_trigger к коммиту:
#        git tag frequencies_trigger && git push origin frequencies_trigger
#    затем его можно удалить
#        sleep 120 && git tag -d frequencies_trigger && git push origin :frequencies_trigger
    jobs:
      - frequencies:
          filters:
            tags:
              only: frequencies_trigger
            branches:
              ignore: /.*/
